version: '3.7'

services:
  diets_postgres:
    image: bitnami/postgresql:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=raulrory
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=diets
    volumes:
      - diets_pg_data:/var/lib/postgresql/data

volumes:
  diets_pg_data: